# Generated by Django 5.1.5 on 2025-02-04 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_installment', models.PositiveIntegerField(help_text='Número de cuota.')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Monto de la cuota a abonar.', max_digits=10)),
                ('due_date_installment', models.DateField(help_text='Fecha en la cual vence la cuota.')),
                ('state', models.CharField(choices=[('PENDIENTE', 'PENDIENTE'), ('PAGADA', 'PAGADA'), ('ATRASADA', 'ATRASADA')], default='PENDIENTE', help_text='Estado de la cuota.', max_length=9)),
                ('purchase', models.ForeignKey(help_text='Compra asociada a la cuota.', on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='purchases.purchase')),
            ],
            options={
                'verbose_name': 'Cuota',
                'verbose_name_plural': 'Cuotas',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(help_text='Fecha en la que se realizó el pago.')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Monto total del pago.', max_digits=10)),
                ('payment_method', models.CharField(choices=[('EFECTIVO', 'EFECTIVO'), ('TARJETA', 'TARJETA'), ('TRANSFERENCIA', 'TRANSFERENCIA')], default='EFECTIVO', help_text='Medio utilizado para realizar el pago.', max_length=20)),
                ('installment', models.ForeignKey(help_text='Cuota asociada al pago.', on_delete=django.db.models.deletion.CASCADE, to='payments.installment')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-payment_date'],
            },
        ),
    ]
