# Generated by Django 5.1.5 on 2025-10-07 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('PRODUCT_ROTATION', 'Rotación de Productos'), ('MOVEMENTS_INPUT_OUTPUT', 'Movimientos Entrada/Salida'), ('SALES_SUMMARY', 'Resumen de Ventas'), ('TOP_PRODUCTS', 'Productos Más Vendidos'), ('PAYMENT_METHODS', 'Métodos de Pago'), ('OVERDUE_INSTALLMENTS', 'Cuotas Vencidas')], max_length=50, verbose_name='Tipo de Reporte')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('PROCESSING', 'Procesando'), ('COMPLETED', 'Completado'), ('FAILED', 'Fallido')], default='PENDING', max_length=20, verbose_name='Estado')),
                ('task_id', models.CharField(max_length=255, unique=True, verbose_name='ID de Tarea')),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/%Y/%m/%d/', verbose_name='Archivo')),
                ('parameters', models.JSONField(default=dict, verbose_name='Parámetros')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Mensaje de Error')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Finalización')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
                'db_table': 'analytics_reports',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='analytics_r_user_id_bd0f15_idx'), models.Index(fields=['status'], name='analytics_r_status_4dcdd6_idx'), models.Index(fields=['task_id'], name='analytics_r_task_id_79da30_idx')],
            },
        ),
    ]
