# Generated by Django 5.1.5 on 2025-09-25 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre de la promoción.', max_length=180)),
                ('active', models.BooleanField(default=False, help_text='Estado de la promoción.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Promoción',
                'verbose_name_plural': 'Promociones',
            },
        ),
        migrations.CreateModel(
            name='PromotionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PERCENTAGE', 'PERCENTAGE'), ('AMOUNT', 'AMOUNT'), ('FIRST_PURCHASE', 'FIRST_PURCHASE')], help_text='Tipo de regla.', max_length=20)),
                ('value', models.DecimalField(decimal_places=2, help_text='Valor que se le aplica al descuento.', max_digits=12)),
                ('priority', models.PositiveIntegerField(default=100, help_text='Prioridad que se le aplica al descuento.')),
                ('start_at', models.DateTimeField(help_text='Fecha y hora que empieza la promoción.')),
                ('end_at', models.DateTimeField(help_text='Fecha en la que termina la promoción.')),
                ('acumulable', models.BooleanField(default=False, help_text='Indica si la promoción es acumulable con otras promociones.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Regla de Promoción',
                'verbose_name_plural': 'Reglas de Promociones',
            },
        ),
        migrations.CreateModel(
            name='PromotionScopeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Promoción por Categoría',
                'verbose_name_plural': 'Promoción por Categorías',
            },
        ),
        migrations.CreateModel(
            name='PromotionScopeLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Promoción por Localización',
                'verbose_name_plural': 'Promoción por Localizaciones',
            },
        ),
        migrations.CreateModel(
            name='PromotionScopeProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Promoción por Producto',
                'verbose_name_plural': 'Promoción por Productos',
            },
        ),
    ]
