# Generated by Django 5.1.5 on 2025-09-25 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0002_initial'),
        ('products', '0002_initial'),
        ('promotions', '0001_initial'),
        ('storage_location', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotion_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='promotion',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotion_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='promotionrule',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotion_rule_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='promotionrule',
            name='promotion',
            field=models.ForeignKey(help_text='Identificador de la promoción.', on_delete=django.db.models.deletion.CASCADE, to='promotions.promotion'),
        ),
        migrations.AddField(
            model_name='promotionrule',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotion_rule_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='promotionscopecategory',
            name='category',
            field=models.ForeignKey(help_text='Identificador de la categoría', on_delete=django.db.models.deletion.CASCADE, to='categories.category'),
        ),
        migrations.AddField(
            model_name='promotionscopecategory',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotion_category_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='promotionscopecategory',
            name='promotion',
            field=models.ForeignKey(help_text='Identificador de la promoción.', on_delete=django.db.models.deletion.CASCADE, to='promotions.promotion'),
        ),
        migrations.AddField(
            model_name='promotionscopecategory',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotion_category_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='promotionscopelocation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotion_location_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='promotionscopelocation',
            name='location',
            field=models.ForeignKey(help_text='Identificador de la localización', on_delete=django.db.models.deletion.CASCADE, to='storage_location.storagelocation'),
        ),
        migrations.AddField(
            model_name='promotionscopelocation',
            name='promotion',
            field=models.ForeignKey(help_text='Identificador de la promoción.', on_delete=django.db.models.deletion.CASCADE, to='promotions.promotion'),
        ),
        migrations.AddField(
            model_name='promotionscopelocation',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotion_location_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='promotionscopeproduct',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotion_product_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='promotionscopeproduct',
            name='product',
            field=models.ForeignKey(help_text='Identificador del producto.', on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AddField(
            model_name='promotionscopeproduct',
            name='promotion',
            field=models.ForeignKey(help_text='Identificador de la promoción.', on_delete=django.db.models.deletion.CASCADE, to='promotions.promotion'),
        ),
        migrations.AddField(
            model_name='promotionscopeproduct',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotion_product_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['active'], name='idx_promotion_active'),
        ),
        migrations.AddIndex(
            model_name='promotionrule',
            index=models.Index(fields=['promotion'], name='idx_pr_promo'),
        ),
        migrations.AddIndex(
            model_name='promotionrule',
            index=models.Index(fields=['priority'], name='idx_pr_priority'),
        ),
        migrations.AddIndex(
            model_name='promotionrule',
            index=models.Index(fields=['start_at', 'end_at'], name='idx_pr_range'),
        ),
        migrations.AddIndex(
            model_name='promotionscopecategory',
            index=models.Index(fields=['category'], name='idx_psc_category'),
        ),
        migrations.AddIndex(
            model_name='promotionscopecategory',
            index=models.Index(fields=['promotion'], name='idx_psc_promotion'),
        ),
        migrations.AddIndex(
            model_name='promotionscopelocation',
            index=models.Index(fields=['location'], name='idx_psl_location'),
        ),
        migrations.AddIndex(
            model_name='promotionscopelocation',
            index=models.Index(fields=['promotion'], name='idx_psl_promotion'),
        ),
        migrations.AddIndex(
            model_name='promotionscopeproduct',
            index=models.Index(fields=['product'], name='idx_psp_product'),
        ),
        migrations.AddIndex(
            model_name='promotionscopeproduct',
            index=models.Index(fields=['promotion'], name='idx_psp_promotion'),
        ),
    ]
