# Generated by Django 5.1.5 on 2025-09-25 14:15

import datetime
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_installment', models.PositiveIntegerField()),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('surcharge_pct', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('discount_pct', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=12)),
                ('due_date', models.DateField(default=datetime.date(2025, 9, 25))),
                ('state', models.CharField(choices=[('PENDING', 'PENDING'), ('PAID', 'PAID'), ('OVERDUE', 'OVERDUE')], default='PENDING', max_length=10)),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InstallmentAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('delta_json', models.JSONField()),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('CASH', 'CASH'), ('CARD', 'CARD'), ('TRANSFER', 'TRANSFER')], default='CASH', max_length=10)),
                ('external_ref', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-payment_date'],
            },
        ),
    ]
