# Generated by Django 5.1.5 on 2025-09-25 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='installment',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installments_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='installmentauditlog',
            name='installment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='payments.installment'),
        ),
        migrations.AddField(
            model_name='installmentauditlog',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installment_audits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='installment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.installment'),
        ),
        migrations.AddField(
            model_name='payment',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='installment',
            index=models.Index(fields=['due_date'], name='idx_installment_due'),
        ),
        migrations.AddIndex(
            model_name='installment',
            index=models.Index(fields=['state'], name='idx_installments_state'),
        ),
        migrations.AddConstraint(
            model_name='installment',
            constraint=models.UniqueConstraint(fields=('purchase', 'num_installment'), name='uq_installment'),
        ),
        migrations.AddIndex(
            model_name='installmentauditlog',
            index=models.Index(fields=['updated_at'], name='idx_installment_audit_changed'),
        ),
        migrations.AddIndex(
            model_name='installmentauditlog',
            index=models.Index(fields=['installment'], name='idx_inst_audit_installment'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['installment'], name='idx_payment_installment'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_date'], name='idx_payment_date'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(fields=('external_ref',), name='uq_payment_extref'),
        ),
    ]
