# Generated by Django 5.1.5 on 2025-09-28 01:50

import api.payments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installment',
            name='due_date',
            field=models.DateField(default=api.payments.models.get_default_due_date),
        ),
    ]
