# Generated by Django 5.1.5 on 2025-01-21 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compras',
            options={'verbose_name': 'Compra', 'verbose_name_plural': 'Compras'},
        ),
        migrations.AlterModelOptions(
            name='cuotas',
            options={'verbose_name': 'Cuota', 'verbose_name_plural': 'Cuotas'},
        ),
        migrations.AlterModelOptions(
            name='mercaderias',
            options={'verbose_name': 'Mercaderia', 'verbose_name_plural': 'Mercaderias'},
        ),
        migrations.AlterModelOptions(
            name='pagos',
            options={'ordering': ['-fecha_pago'], 'verbose_name': 'Pago', 'verbose_name_plural': 'Pagos'},
        ),
        migrations.RemoveField(
            model_name='pagos',
            name='compra',
        ),
        migrations.RemoveField(
            model_name='pagos',
            name='es_adelantado',
        ),
        migrations.RemoveField(
            model_name='pagos',
            name='metodo_pago',
        ),
        migrations.RemoveField(
            model_name='pagos',
            name='recargo_aplicado',
        ),
        migrations.AddField(
            model_name='compras',
            name='cuotas_totales',
            field=models.IntegerField(default=1, help_text='Total de cuotas a pagar.'),
        ),
        migrations.AddField(
            model_name='pagos',
            name='cuotas',
            field=models.ForeignKey(default=1, help_text='Cuota asociada al pago.', on_delete=django.db.models.deletion.CASCADE, to='api.cuotas'),
        ),
        migrations.AddField(
            model_name='pagos',
            name='medio_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta'), ('TRANSFERENCIA', 'Transferencia')], default='EFECTIVO', help_text='Medio utilizado para realizar el pago.', max_length=20),
        ),
        migrations.AlterField(
            model_name='compras',
            name='fecha_compra',
            field=models.DateField(help_text='Fecha en la cual la compra se realiza.'),
        ),
        migrations.AlterField(
            model_name='compras',
            name='fecha_vencimiento',
            field=models.DateField(help_text='Fecha de vencimiento del pago.'),
        ),
        migrations.AlterField(
            model_name='compras',
            name='monto_total',
            field=models.DecimalField(decimal_places=2, help_text='Monto total de la compra.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='compras',
            name='usuario',
            field=models.ForeignKey(help_text='Usuario que realiza la compra.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cuotas',
            name='compra',
            field=models.ForeignKey(help_text='Compra asociada a la cuota.', on_delete=django.db.models.deletion.CASCADE, to='api.compras'),
        ),
        migrations.AlterField(
            model_name='cuotas',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADA', 'Pagada'), ('ATRASADA', 'Atrasada')], default='PENDIENTE', help_text='Estad de la cuota.', max_length=9),
        ),
        migrations.AlterField(
            model_name='cuotas',
            name='fecha_vencimiento',
            field=models.DateField(help_text='Fecha en la cual vence la cuota.'),
        ),
        migrations.AlterField(
            model_name='cuotas',
            name='monto',
            field=models.DecimalField(decimal_places=2, help_text='Monto de la cuota a abonar.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='cuotas',
            name='nro_cuota',
            field=models.IntegerField(help_text='Número de cuota.'),
        ),
        migrations.AlterField(
            model_name='mercaderias',
            name='cod_mercaderia',
            field=models.CharField(help_text='Código del producto.', max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='mercaderias',
            name='marca',
            field=models.CharField(help_text='Marca asociada al producto.', max_length=45),
        ),
        migrations.AlterField(
            model_name='mercaderias',
            name='modelo',
            field=models.CharField(help_text='Modelo asociado al producto.', max_length=100),
        ),
        migrations.AlterField(
            model_name='mercaderias',
            name='nombre',
            field=models.CharField(help_text='Nombre del producto.', max_length=100),
        ),
        migrations.AlterField(
            model_name='mercaderias',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, help_text='Precio del producto por unidad.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='mercaderias',
            name='stock',
            field=models.IntegerField(help_text='Cantidad del producto en stock'),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='descuento_aplicado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Descuento aplicado en el pago, si corresponde.', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='fecha_pago',
            field=models.DateField(help_text='Fecha en la que se realizó el pago.'),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='monto',
            field=models.DecimalField(decimal_places=2, help_text='Monto total del pago.', max_digits=10),
        ),
        migrations.CreateModel(
            name='DetallesCompras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_producto', models.IntegerField(help_text='Cantidad del producto.')),
                ('compras', models.ForeignKey(help_text='Compra asociada a la mercadería.', on_delete=django.db.models.deletion.CASCADE, to='api.compras')),
                ('mercaderias', models.ForeignKey(help_text='Mercadería asociada a la compra.', on_delete=django.db.models.deletion.CASCADE, to='api.mercaderias')),
            ],
        ),
    ]
