# Generated by Django 5.1.5 on 2025-01-21 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_compras_options_alter_cuotas_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagos',
            name='cuotas',
            field=models.ForeignKey(help_text='Cuota asociada al pago.', on_delete=django.db.models.deletion.CASCADE, to='api.cuotas'),
        ),
    ]
