# Generated by Django 5.1.5 on 2025-01-21 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_pagos_cuotas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detallescompras',
            old_name='cantidad_producto',
            new_name='cantidad_productos',
        ),
    ]
