# Generated by Django 5.1.5 on 2025-01-21 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_cantidad_producto_detallescompras_cantidad_productos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DetallesCompras',
        ),
    ]
