# Generated by Django 5.1.5 on 2025-01-21 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_delete_detallescompras'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetallesCompras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_productos', models.IntegerField(help_text='Cantidad del producto.')),
                ('compras', models.ForeignKey(help_text='Compra asociada a la mercadería.', on_delete=django.db.models.deletion.CASCADE, to='api.compras')),
                ('mercaderias', models.ForeignKey(help_text='Mercadería asociada a la compra.', on_delete=django.db.models.deletion.CASCADE, to='api.mercaderias')),
            ],
        ),
    ]
