# Generated by Django 5.1.5 on 2025-01-21 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_detallescompras'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detallescompras',
            options={'verbose_name': 'Detalle Compra', 'verbose_name_plural': 'Detalles Compras'},
        ),
    ]
