# Generated by Django 5.1.5 on 2025-01-21 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_mercaderias_products_alter_products_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallescompras',
            name='products',
            field=models.ForeignKey(help_text='Productos asociado a la compra.', on_delete=django.db.models.deletion.CASCADE, to='api.products'),
        ),
    ]
