# Generated by Django 5.1.5 on 2025-01-23 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_detallescompras_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallescompras',
            name='compras',
            field=models.ForeignKey(help_text='Compra asociada al producto.', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='api.compras'),
        ),
    ]
