# Generated by Django 5.1.5 on 2025-01-23 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_detallescompras_compras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compras',
            name='cuotas_totales',
            field=models.PositiveIntegerField(default=1, help_text='Total de cuotas a pagar.'),
        ),
        migrations.AlterField(
            model_name='cuotas',
            name='nro_cuota',
            field=models.PositiveIntegerField(help_text='Número de cuota.'),
        ),
        migrations.AlterField(
            model_name='detallescompras',
            name='cantidad_productos',
            field=models.PositiveIntegerField(help_text='Cantidad del producto.'),
        ),
        migrations.AlterField(
            model_name='products',
            name='stock',
            field=models.PositiveIntegerField(help_text='Cantidad del producto en stock'),
        ),
    ]
