# Generated by Django 5.1.5 on 2025-01-24 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_cuotas_compra_notificacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuotas',
            old_name='compra',
            new_name='compras',
        ),
    ]
