# Generated by Django 5.1.5 on 2025-01-24 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_compra_cuotas_compras'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagos',
            name='descuento_aplicado',
        ),
        migrations.AddField(
            model_name='compras',
            name='cuota_actual',
            field=models.PositiveIntegerField(default=1, help_text='Total de cuotas a pagar.'),
        ),
        migrations.AddField(
            model_name='compras',
            name='descuento_aplicado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Descuento aplicado en el pago, si corresponde.', max_digits=5, null=True),
        ),
    ]
