# Generated by Django 5.1.5 on 2025-01-25 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_pagos_descuento_aplicado_compras_cuota_actual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuotas',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADA', 'Pagada'), ('ATRASADA', 'Atrasada')], default='Pendiente', help_text='Estad de la cuota.', max_length=9),
        ),
    ]
