# Generated by Django 5.1.5 on 2025-01-25 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_cuotas_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuotas',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'PENDIENTE'), ('PAGADA', 'PAGADA'), ('ATRASADA', 'ATRASADA')], default='PENDIENTE', help_text='Estad de la cuota.', max_length=9),
        ),
    ]
