# Generated by Django 5.1.5 on 2025-01-25 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_cuotas_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuotas',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADA', 'Pagada'), ('ATRASADA', 'Atrasada')], default='PENDIENTE', help_text='Estado de la cuota.', max_length=9),
        ),
    ]
