# Generated by Django 5.1.5 on 2025-01-26 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_cuotas_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuotas',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'PENDIENTE'), ('PAGADA', 'PAGADA'), ('ATRASADA', 'ATRASADA')], default='PENDIENTE', help_text='Estado de la cuota.', max_length=9),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='medio_pago',
            field=models.CharField(choices=[('EFECTIVO', 'EFECTIVO'), ('TARJETA', 'TARJETA'), ('TRANSFERENCIA', 'TRANSFERENCIA')], default='EFECTIVO', help_text='Medio utilizado para realizar el pago.', max_length=20),
        ),
    ]
