# Generated by Django 5.1.5 on 2025-01-27 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_cuotas_estado_alter_pagos_medio_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='compras',
            name='monto_pagado',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Monto que se ha pagado.', max_digits=10),
        ),
    ]
