# Generated by Django 5.1.5 on 2025-09-25 14:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_code', models.CharField(blank=True, max_length=120, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('reason', models.CharField(choices=[('PURCHASE_ENTRY', 'PURCHASE_ENTRY'), ('EXIT_SALE', 'EXIT_SALE'), ('TRANSFER', 'TRANSFER'), ('ADJUSTMENT', 'ADJUSTMENT'), ('RETURN_ENTRY', 'RETURN_ENTRY'), ('RETURN_OUTPUT', 'RETURN_OUTPUT')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('reference_type', models.CharField(choices=[('PURCHASE', 'PURCHASE'), ('PAYMENT', 'PAYMENT'), ('MANUAL', 'MANUAL'), ('SALE', 'SALE')], max_length=20)),
                ('reference_id', models.IntegerField(blank=True, null=True)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
            },
        ),
        migrations.CreateModel(
            name='InventoryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='Cantidad de productos.')),
                ('batch_code', models.CharField(blank=True, default='__NULL__', help_text='Código de lote (si corresponde)', max_length=120)),
                ('expiry_date', models.DateField(blank=True, default=datetime.date(9999, 12, 31), help_text='Fecha de vencimiento del lote')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Inventario',
                'verbose_name_plural': 'Inventarios',
                'ordering': ['product', '-quantity'],
            },
        ),
        migrations.CreateModel(
            name='StockSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_code', models.CharField(blank=True, max_length=120, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('last_movement_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Materialización reporte',
                'verbose_name_plural': 'Materialización reportes',
            },
        ),
    ]
