# Generated by Django 5.1.5 on 2025-09-25 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventories', '0001_initial'),
        ('products', '0001_initial'),
        ('storage_location', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymovement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='from_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movements_from', to='storage_location.storagelocation'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='to_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movements_to', to='storage_location.storagelocation'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventoryrecord',
            name='location',
            field=models.ForeignKey(help_text='Identificador del Depósito.', on_delete=django.db.models.deletion.PROTECT, to='storage_location.storagelocation'),
        ),
        migrations.AddField(
            model_name='inventoryrecord',
            name='product',
            field=models.ForeignKey(help_text='Identificador del Producto.', on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AddField(
            model_name='inventoryrecord',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_record_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stocksnapshot',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage_location.storagelocation'),
        ),
        migrations.AddField(
            model_name='stocksnapshot',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AddField(
            model_name='stocksnapshot',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_snapshots_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['product'], name='idx_im_product'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['occurred_at'], name='idx_im_occurred'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['from_location'], name='idx_im_from'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['to_location'], name='idx_im_to'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['reference_type', 'reference_id'], name='idx_im_ref'),
        ),
        migrations.AddIndex(
            model_name='inventoryrecord',
            index=models.Index(fields=['product'], name='idx_invrc_product'),
        ),
        migrations.AddIndex(
            model_name='inventoryrecord',
            index=models.Index(fields=['location'], name='idx_invrec_location'),
        ),
        migrations.AddIndex(
            model_name='inventoryrecord',
            index=models.Index(fields=['product', 'location', 'batch_code', 'expiry_date'], name='idx_invrec_prod_loc_bat_exp'),
        ),
        migrations.AddConstraint(
            model_name='inventoryrecord',
            constraint=models.UniqueConstraint(fields=('product', 'location', 'batch_code', 'expiry_date'), name='uq_invrec'),
        ),
        migrations.AddIndex(
            model_name='stocksnapshot',
            index=models.Index(fields=['product'], name='idx_snapshot_product'),
        ),
        migrations.AddIndex(
            model_name='stocksnapshot',
            index=models.Index(fields=['location'], name='idx_snapshot_location'),
        ),
        migrations.AddConstraint(
            model_name='stocksnapshot',
            constraint=models.UniqueConstraint(fields=('product', 'location', 'batch_code', 'expiry_date'), name='uq_snapshot'),
        ),
    ]
