# Generated by Django 5.1.5 on 2025-09-25 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('purchase_confirmed', 'Compra Confirmada'), ('installment_due_7d', 'Cuota Vence en 7 Días'), ('installment_paid', 'Cuota Pagada'), ('payment_error', 'Error en Pago'), ('overdue_notice', 'Aviso de Vencimiento'), ('overdue_surcharge_notice', 'Aviso de Recargo por Vencimiento'), ('created_account', 'Cuenta Creada')], help_text='Código de template.', max_length=100, unique=True)),
                ('subject', models.CharField(help_text='Asunto.', max_length=180)),
                ('head_html', models.TextField(help_text='Encabezado del HTML.')),
                ('footer_html', models.TextField(help_text='Pie de página del HTML.')),
                ('active', models.BooleanField(default=True, help_text='Estado del template.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_template_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_template_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plantilla de Notificación',
                'verbose_name_plural': 'Plantillas de Notificaciones',
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context_json', models.JSONField(blank=True, help_text='Payload dinámico.', null=True)),
                ('recipient_email', models.CharField(max_length=255)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SENT', 'SENT'), ('ERROR', 'ERROR')], default='SENT', max_length=10)),
                ('error_message', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_logs_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_logs_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='Usuario destinatario.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, db_column='template_code', help_text='Código de template usado.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.notificationtemplate', to_field='code')),
            ],
            options={
                'verbose_name': 'Log de Notificación',
                'verbose_name_plural': 'Logs de Notificaciones',
            },
        ),
        migrations.AddConstraint(
            model_name='notificationtemplate',
            constraint=models.UniqueConstraint(fields=('code',), name='uq_nt_code'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['user'], name='idx_nl_user'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['status'], name='idx_nl_status'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['sent_at'], name='idx_nl_sent'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['template'], name='idx_nl_tpl'),
        ),
    ]
