# Generated by Django 5.1.5 on 2025-10-07 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationlog',
            name='time_duration',
            field=models.FloatField(blank=True, help_text='Tiempo en segundos que tomó el envío.', null=True),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='status',
            field=models.CharField(choices=[('SENT', 'Send'), ('ERROR', 'Error'), ('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('FAILED', 'Failed')], default='SENT', max_length=10),
        ),
    ]
