# Generated by Django 5.1.5 on 2025-02-04 23:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateField(help_text='Fecha en la cual la compra se realiza.')),
                ('due_date', models.DateField(help_text='Fecha de vencimiento del pago.')),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Monto total de la compra.', max_digits=10)),
                ('total_installments_count', models.PositiveIntegerField(default=1, help_text='Total de cuotas a pagar.')),
                ('discount_applied', models.DecimalField(blank=True, decimal_places=2, help_text='Descuento aplicado en el pago, si corresponde.', max_digits=5, null=True)),
                ('current_installment', models.PositiveIntegerField(default=1, help_text='Cuota actual en la que se encuentra el pago.')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, help_text='Monto que se ha pagado.', max_digits=10)),
                ('user', models.ForeignKey(help_text='Usuario que realiza la compra.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
            },
        ),
        migrations.CreateModel(
            name='PurchaseDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant_product', models.PositiveIntegerField(help_text='Cantidad del producto comprado.')),
                ('product', models.ForeignKey(help_text='Producto asociado a la compra.', on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('purchase', models.ForeignKey(help_text='Compra asociada al producto.', on_delete=django.db.models.deletion.CASCADE, related_name='details', to='purchases.purchase')),
            ],
            options={
                'verbose_name': 'Detalle Compra',
                'verbose_name_plural': 'Detalles Compras',
            },
        ),
    ]
