# Generated by Django 5.1.5 on 2025-09-25 14:15

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateTimeField()),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('total_installments_count', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('OPEN', 'OPEN'), ('PAID', 'PAID'), ('CANCELLED', 'CANCELLED')], default='OPEN', max_length=10)),
                ('discount_applied', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
            },
        ),
        migrations.CreateModel(
            name='PurchaseDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='Cantidad del producto comprado.')),
                ('unit_price_at_purchase', models.DecimalField(decimal_places=2, help_text='Precio unitario del producto.', max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Subtotal de producto.', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Detalle Compra',
                'verbose_name_plural': 'Detalles Compras',
            },
        ),
    ]
