# Generated by Django 5.1.5 on 2025-02-04 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='discount_applied',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Descuento aplicado en el pago, si corresponde.', max_digits=5, null=True),
        ),
    ]
