# Generated by Django 5.1.5 on 2025-09-25 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_initial'),
        ('purchases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchase',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchase',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchasedetail',
            name='product',
            field=models.ForeignKey(help_text='Producto asociado a la compra.', on_delete=django.db.models.deletion.PROTECT, to='products.product'),
        ),
        migrations.AddField(
            model_name='purchasedetail',
            name='purchase',
            field=models.ForeignKey(help_text='Compra asociada al producto.', on_delete=django.db.models.deletion.CASCADE, related_name='details', to='purchases.purchase'),
        ),
        migrations.AddField(
            model_name='purchasedetail',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_detail_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['user'], name='idx_purchase_user'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['status'], name='idx_purchase_status'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['purchase_date'], name='idx_purchase_date'),
        ),
        migrations.AddIndex(
            model_name='purchasedetail',
            index=models.Index(fields=['purchase'], name='idx_pd_purchase'),
        ),
        migrations.AddIndex(
            model_name='purchasedetail',
            index=models.Index(fields=['product'], name='idx_pd_product'),
        ),
    ]
