# Generated by Django 5.1.5 on 2025-01-27 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuotas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_cuota', models.PositiveIntegerField(help_text='Número de cuota.')),
                ('monto', models.DecimalField(decimal_places=2, help_text='Monto de la cuota a abonar.', max_digits=10)),
                ('fecha_vencimiento', models.DateField(help_text='Fecha en la cual vence la cuota.')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'PENDIENTE'), ('PAGADA', 'PAGADA'), ('ATRASADA', 'ATRASADA')], default='PENDIENTE', help_text='Estado de la cuota.', max_length=9)),
                ('compras', models.ForeignKey(help_text='Compra asociada a la cuota.', on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='compras.compras')),
            ],
            options={
                'verbose_name': 'Cuota',
                'verbose_name_plural': 'Cuotas',
            },
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField(help_text='Fecha en la que se realizó el pago.')),
                ('monto', models.DecimalField(decimal_places=2, help_text='Monto total del pago.', max_digits=10)),
                ('medio_pago', models.CharField(choices=[('EFECTIVO', 'EFECTIVO'), ('TARJETA', 'TARJETA'), ('TRANSFERENCIA', 'TRANSFERENCIA')], default='EFECTIVO', help_text='Medio utilizado para realizar el pago.', max_length=20)),
                ('cuotas', models.ForeignKey(help_text='Cuota asociada al pago.', on_delete=django.db.models.deletion.CASCADE, to='pagos.cuotas')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-fecha_pago'],
            },
        ),
    ]
