# Generated by Django 5.1.5 on 2025-09-25 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StorageLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del depósito.', max_length=180)),
                ('street', models.CharField(help_text='Calle (ej: Av. Corrientes).', max_length=255)),
                ('street_number', models.CharField(help_text='Altura (ej: 1543).', max_length=10)),
                ('floor_unit', models.CharField(blank=True, help_text='Piso/unidad (si aplica).', max_length=10, null=True)),
                ('state', models.CharField(help_text='Provincia/estado.', max_length=120)),
                ('city', models.CharField(help_text='Ciudad.', max_length=120)),
                ('country', models.CharField(help_text='País.', max_length=120)),
                ('type', models.CharField(choices=[('WH', 'WAREHOUSE'), ('SB', 'SUBWAREHOUSE'), ('SH', 'SHELF'), ('OT', 'OTHER')], default='WH', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Depósito',
                'verbose_name_plural': 'Depósitos',
                'ordering': ['name'],
            },
        ),
    ]
