# Generated by Django 5.1.5 on 2025-09-25 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('storage_location', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='storagelocation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storage_locations_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='storagelocation',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Nodo padre en la jerarquía.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='storage_location.storagelocation'),
        ),
        migrations.AddField(
            model_name='storagelocation',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storage_locations_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='storagelocation',
            index=models.Index(fields=['parent'], name='idx_location_parent'),
        ),
        migrations.AddIndex(
            model_name='storagelocation',
            index=models.Index(fields=['type'], name='idx_location_type'),
        ),
        migrations.AddIndex(
            model_name='storagelocation',
            index=models.Index(fields=['name'], name='idx_location_name'),
        ),
        migrations.AddConstraint(
            model_name='storagelocation',
            constraint=models.UniqueConstraint(fields=('parent', 'type', 'name'), name='uq_location'),
        ),
    ]
