# Generated by Django 5.1.5 on 2025-01-27 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compra', models.DateField(help_text='Fecha en la cual la compra se realiza.')),
                ('fecha_vencimiento', models.DateField(help_text='Fecha de vencimiento del pago.')),
                ('monto_total', models.DecimalField(decimal_places=2, help_text='Monto total de la compra.', max_digits=10)),
                ('cuotas_totales', models.PositiveIntegerField(default=1, help_text='Total de cuotas a pagar.')),
                ('descuento_aplicado', models.DecimalField(blank=True, decimal_places=2, help_text='Descuento aplicado en el pago, si corresponde.', max_digits=5, null=True)),
                ('cuota_actual', models.PositiveIntegerField(default=1, help_text='Total de cuotas a pagar.')),
                ('monto_pagado', models.DecimalField(decimal_places=2, default=0.0, help_text='Monto que se ha pagado.', max_digits=10)),
                ('usuario', models.ForeignKey(help_text='Usuario que realiza la compra.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
            },
        ),
        migrations.CreateModel(
            name='DetallesCompras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_productos', models.PositiveIntegerField(help_text='Cantidad del producto.')),
                ('compras', models.ForeignKey(help_text='Compra asociada al producto.', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='compras.compras')),
                ('productos', models.ForeignKey(help_text='Productos asociado a la compra.', on_delete=django.db.models.deletion.CASCADE, to='productos.productos')),
            ],
            options={
                'verbose_name': 'Detalle Compra',
                'verbose_name_plural': 'Detalles Compras',
            },
        ),
    ]
